# Generated by Django 4.0.2 on 2022-02-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_ticket_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='amc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.amc'),
        ),
    ]
